print('hello world'.capitalize())
print('hello world'.upper())
print('Hello world'.lower())
print('hello world'.__len__())
print(len('hello world'))
print('Hello world'.replace('world', 'Python'))
print("DK's Python \"tutorials\"")
print("\\")
print("Hello \nworld")
print("Hello \t\tworld")
print("\a")
print('Hello \nworld')
