puts('hello world'.capitalize())
puts('hello world'.upcase())
puts('hello world'.length())
puts('Hello world'.sub('world', 'Ruby'))
puts("DK's Ruby \"tutorials\"")
puts("\\")
puts("Hello \nworld")
puts("Hello \t\tworld")
puts("\a")
print('Hello \nworld')